_target_: ogbench.evaluator.evaluator.TBEvaluator
task: ${dataset.parameters.task}
task_level: ${dataset.parameters.task_level}
num_classes: ${dataset.parameters.num_classes}

# Metrics
metrics: [accuracy, precision, recall, auroc, f1_weighted] # Available options: accuracy, auroc, precision, recall, f1_weighted
