_target_: ogbench.model.TBModel

model_name: GATv4
model_domain: graph

feature_encoder:
  _target_: ogbench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 1
  proj_dropout: 0.0

backbone:
  _target_: ogbench.nn.backbones.${model.model_name}
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: [64, 128]
  out_channels: 1
  heads: [3, 3]
  dropout: 0.25
  act: relu
  which_layer: ["layer1", "layer2", "layer3"]
  use_layer_norm: true
  num_nodes: ${dataset.parameters.num_nodes}
  weight_initializer: "xavier"

backbone_wrapper:
  _target_: ogbench.nn.wrappers.GATv4Wrapper
  _partial_: true
  wrapper_name: GATv4Wrapper
  out_channels: ${get_flattened_channels:${model.backbone.out_channels},3}
  num_nodes: ${dataset.parameters.num_nodes}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}
  features_to_keep: ${oc.select:dataset.parameters.features_to_keep,null} # list of features to keep in the final output
  residual_connections: false # whether to use residual connections in the GNN

readout:
  _target_: ogbench.nn.readouts.${model.readout.readout_name}
  readout_name: NoReadOut
  num_cell_dimensions: ${model.backbone_wrapper.num_cell_dimensions}
  hidden_dim: ${model.backbone_wrapper.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: mean
compile: false
