#!/bin/bash

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=gcn \
    model.feature_encoder.out_channels=64,128,256 \
    model.backbone.num_layers=2,4 \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.act=relu \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[0\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=graph_sage \
    model.feature_encoder.out_channels=64,128,256 \
    model.backbone.num_layers=2,4 \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.act=relu \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[1\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=gin \
    model.feature_encoder.out_channels=64,128,256 \
    model.backbone.num_layers=2,4 \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.act=relu \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[2\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=gatv2 \
    model.feature_encoder.out_channels=64,128,256 \
    model.backbone.heads=2,4 \
    model.backbone.num_layers=2,4 \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.act=relu \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[3\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=chebnet \
    model.feature_encoder.out_channels=64,128,256 \
    model.backbone.K=2,3 \
    model.backbone.num_layers=2,4 \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[4\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=mlp \
    model.backbone.hidden_channels=\[128,64,32\],\[512,256,128\],\[1024,512,256\] \
    model.backbone.dropout=0.2,0.4,0.6 \
    model.backbone.act=relu,tanh \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[5\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=gatv4 \
    model.backbone.heads=\[3,3\] \
    model.backbone.hidden_channels=\[8,16\],\[64,128\],\[128,256\] \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.act=relu \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[6\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &

python -m ogbench \
    dataset=covidaki \
    dataset.loader.parameters.adjacency_threshold=0.75,0.8,0.85 \
    dataset.split_params.data_seed=1,3,5 \
    dataset.dataloader_params.batch_size=8,16 \
    dataset.loader.parameters.node_sample_ratio=full \
    dataset.loader.parameters.method=variance,random,correlation \
    model=sagn \
    model.backbone.num_layers=2,4 \
    model.backbone.hidden_channels=128,256 \
    model.backbone.dropout=0.2,0.4 \
    model.backbone.alpha=0.5,0.8 \
    model.readout.pooling_type=mean,sum \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0004 \
    callbacks.early_stopping.patience=50 \
    trainer.check_val_every_n_epoch=1 \
    trainer.max_epochs=1000 \
    trainer.min_epochs=50 \
    trainer.devices=\[7\] \
    logger.wandb.project=pruned_grid_search \
    tags="[first_grid_search]" \
    --multirun &
