#!/bin/bash
# shellcheck disable=SC2102
# Fixed/original-split best-per-(model, dataset) runs with the original adjacency thresholds.
# Adds learnable marker identity before message passing for the node-identity rebuttal.
# W&B project: ogbench_rebuttal_node_identity
#
# IMPORTANT: every job must go through launch() so CPU threads are capped.
# Do not background bare `python -m ogbench ... &` in this file.
#
# Launch: bash scripts/rerun_best_node_identity.sh
# Optional: MAX_PARALLEL=8 N_THREADS=2 bash scripts/rerun_best_node_identity.sh

set -euo pipefail

ROOT_DIR="${ROOT_DIR:-/scratch/lcornelis/ogbench}"
WANDB_PROJECT="${WANDB_PROJECT:-ogbench_rebuttal_node_identity}"
WANDB_ENTITY="${WANDB_ENTITY:-bioshape-lab}"
N_GPUS="${N_GPUS:-8}"
MAX_PARALLEL="${MAX_PARALLEL:-8}"
# Cap CPU threads per job so parallel jobs do not oversubscribe OpenMP/MKL
# and thrash the machine / starve GPUs.
N_THREADS="${N_THREADS:-2}"

running=0

launch() {
  local gpu="$1"
  shift
  echo "[gpu ${gpu}] threads=${N_THREADS} $*"
  CUDA_VISIBLE_DEVICES="${gpu}" \
    OMP_NUM_THREADS="${N_THREADS}" \
    MKL_NUM_THREADS="${N_THREADS}" \
    OPENBLAS_NUM_THREADS="${N_THREADS}" \
    NUMEXPR_NUM_THREADS="${N_THREADS}" \
    TORCH_NUM_THREADS="${N_THREADS}" \
    "$@" &
  running=$((running + 1))
  if (( running >= MAX_PARALLEL )); then
    wait -n || true
    running=$((running - 1))
  fi
}


# chebnet / addneuromed / seed=42
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[chebnet,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / addneuromed / seed=123
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[chebnet,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / addneuromed / seed=456
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[chebnet,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / brca / seed=42
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[chebnet,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / brca / seed=123
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[chebnet,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / brca / seed=456
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[chebnet,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / motrpac / seed=42
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[chebnet,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / motrpac / seed=123
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[chebnet,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / motrpac / seed=456
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[chebnet,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / parkinsons / seed=42
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[chebnet,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / parkinsons / seed=123
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[chebnet,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# chebnet / parkinsons / seed=456
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=chebnet \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[chebnet,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / addneuromed / seed=42
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[gatv2,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / addneuromed / seed=123
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[gatv2,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / addneuromed / seed=456
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[gatv2,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / brca / seed=42
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[gatv2,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / brca / seed=123
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[gatv2,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / brca / seed=456
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[gatv2,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / motrpac / seed=42
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[gatv2,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / motrpac / seed=123
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[gatv2,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / motrpac / seed=456
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[gatv2,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / parkinsons / seed=42
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[gatv2,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / parkinsons / seed=123
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[gatv2,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv2 / parkinsons / seed=456
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gatv2 \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[gatv2,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / addneuromed / seed=42
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[gatv4,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=false \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / addneuromed / seed=123
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[gatv4,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / addneuromed / seed=456
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[gatv4,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=false \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / brca / seed=42
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[gatv4,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=false \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / brca / seed=123
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[gatv4,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=false \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / brca / seed=456
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[gatv4,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / motrpac / seed=42
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[gatv4,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / motrpac / seed=123
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[gatv4,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / motrpac / seed=456
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[gatv4,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / parkinsons / seed=42
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[gatv4,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / parkinsons / seed=123
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[gatv4,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=false \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gatv4 / parkinsons / seed=456
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gatv4 \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[gatv4,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64] \
    model.backbone.heads=[4,4] \
    model.backbone.use_layer_norm=true \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / addneuromed / seed=42
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[gcn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / addneuromed / seed=123
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[gcn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / addneuromed / seed=456
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[gcn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / brca / seed=42
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[gcn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / brca / seed=123
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[gcn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / brca / seed=456
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[gcn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / motrpac / seed=42
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[gcn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / motrpac / seed=123
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[gcn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / motrpac / seed=456
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[gcn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / parkinsons / seed=42
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[gcn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / parkinsons / seed=123
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[gcn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gcn / parkinsons / seed=456
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gcn \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[gcn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / addneuromed / seed=42
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[gin,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / addneuromed / seed=123
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[gin,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / addneuromed / seed=456
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[gin,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / brca / seed=42
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[gin,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / brca / seed=123
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[gin,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / brca / seed=456
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[gin,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / motrpac / seed=42
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[gin,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / motrpac / seed=123
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[gin,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / motrpac / seed=456
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[gin,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / parkinsons / seed=42
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[gin,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / parkinsons / seed=123
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[gin,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gin / parkinsons / seed=456
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gin \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[gin,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / addneuromed / seed=42
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[gps,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / addneuromed / seed=123
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[gps,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / addneuromed / seed=456
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[gps,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / brca / seed=42
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[gps,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.0006 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / brca / seed=123
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[gps,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.0006 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / brca / seed=456
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[gps,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.0006 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / motrpac / seed=42
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[gps,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / motrpac / seed=123
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[gps,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / motrpac / seed=456
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[gps,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[LapPE] \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / parkinsons / seed=42
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[gps,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / parkinsons / seed=123
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[gps,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# gps / parkinsons / seed=456
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=gps \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[gps,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    model.encodings=[RWSE] \
    dataset.loader.parameters.adjacency_threshold=0.0216 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / addneuromed / seed=42
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[mlp,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.2378 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / addneuromed / seed=123
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[mlp,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.2378 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / addneuromed / seed=456
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[mlp,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.2378 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / brca / seed=42
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[mlp,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[64,128,32] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / brca / seed=123
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[mlp,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[64,128,32] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / brca / seed=456
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[mlp,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[64,128,32] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / motrpac / seed=42
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[mlp,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / motrpac / seed=123
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[mlp,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / motrpac / seed=456
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[mlp,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / parkinsons / seed=42
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[mlp,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=null \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / parkinsons / seed=123
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[mlp,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# mlp / parkinsons / seed=456
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=mlp \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[mlp,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=no_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=[32,64,16] \
    model.backbone.norm=batch \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / addneuromed / seed=42
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[graph_sage,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / addneuromed / seed=123
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[graph_sage,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / addneuromed / seed=456
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[graph_sage,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.1786 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / brca / seed=42
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[graph_sage,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / brca / seed=123
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[graph_sage,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / brca / seed=456
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[graph_sage,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / motrpac / seed=42
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[graph_sage,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / motrpac / seed=123
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[graph_sage,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / motrpac / seed=456
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[graph_sage,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=16 \
    model.backbone.num_layers=4 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / parkinsons / seed=42
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[graph_sage,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / parkinsons / seed=123
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[graph_sage,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# graph_sage / parkinsons / seed=456
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=graph_sage \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[graph_sage,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.feature_encoder.out_channels=64 \
    model.backbone.num_layers=2 \
    dataset.loader.parameters.adjacency_threshold=0.0005 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / addneuromed / seed=42
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=addneuromed \
    seed=42 \
    logger.wandb.tags=[sagn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.2996 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / addneuromed / seed=123
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=addneuromed \
    seed=123 \
    logger.wandb.tags=[sagn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.2996 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / addneuromed / seed=456
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=addneuromed \
    seed=456 \
    logger.wandb.tags=[sagn,addneuromed,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=1.0 \
    dataset.loader.parameters.method=variance \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.2996 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / brca / seed=42
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=brca \
    seed=42 \
    logger.wandb.tags=[sagn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / brca / seed=123
launch 4 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=brca \
    seed=123 \
    logger.wandb.tags=[sagn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / brca / seed=456
launch 5 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=brca \
    seed=456 \
    logger.wandb.tags=[sagn,brca,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=string \
    dataset.loader.parameters.node_sample_ratio=0.8 \
    dataset.loader.parameters.method=distance_correlation \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=16 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=4 \
    dataset.loader.parameters.adjacency_threshold=0.4 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / motrpac / seed=42
launch 6 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=motrpac \
    seed=42 \
    logger.wandb.tags=[sagn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / motrpac / seed=123
launch 7 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=motrpac \
    seed=123 \
    logger.wandb.tags=[sagn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / motrpac / seed=456
launch 0 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=motrpac \
    seed=456 \
    logger.wandb.tags=[sagn,motrpac,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.5 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.0001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=4 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0693 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / parkinsons / seed=42
launch 1 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=parkinsons \
    seed=42 \
    logger.wandb.tags=[sagn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / parkinsons / seed=123
launch 2 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=parkinsons \
    seed=123 \
    logger.wandb.tags=[sagn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

# sagn / parkinsons / seed=456
launch 3 python -m ogbench \
    gene_identity=learnable \
    model=sagn \
    dataset=parkinsons \
    seed=456 \
    logger.wandb.tags=[sagn,parkinsons,hpsearch,best_rerun,node_identity,learnable] \
    experiment=omics_readout \
    dataset.loader.parameters.adjacency_method=wgcna \
    dataset.loader.parameters.node_sample_ratio=0.3 \
    dataset.loader.parameters.method=random \
    optimizer.parameters.lr=0.001 \
    optimizer.parameters.weight_decay=0.0 \
    model.backbone.dropout=0.1 \
    model.backbone.hidden_channels=64 \
    model.backbone.num_layers=2 \
    model.backbone.num_heads=2 \
    dataset.loader.parameters.adjacency_threshold=0.0043 \
    model.readout.fc_dropout=0.1 \
    logger.wandb.entity="${WANDB_ENTITY}" \
    logger.wandb.project="${WANDB_PROJECT}" \
    paths.root_dir="${ROOT_DIR}" \
    trainer.devices=\[0\]

wait
