"""Utility functions for dataset processing."""

import json
import os
import tempfile
from datetime import datetime
from typing import Any

import huggingface_hub
import requests


def download_file(url: str, file_path: str) -> None:
    """Download a file from URL to local path.

    Args:
        url: URL to download from
        file_path: Local path to save the file
    """
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    response = requests.get(url, stream=True, timeout=30)
    response.raise_for_status()

    with open(file_path, 'wb') as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)


def create_dataset_metadata(
    dataset_name: str,
    download_urls: dict[str, str],
    num_samples: int,
    num_features: int,
    target_stats: dict[str, float],
    preprocessing_notes: str | None = None,
) -> dict[str, Any]:
    """Create metadata dictionary for a dataset.

    Args:
        dataset_name: Name of the dataset
        download_urls: Dictionary mapping dataset keys to download URLs
        num_samples: Number of samples in the dataset
        num_features: Number of features in the dataset
        target_stats: Statistics about the target variable
        preprocessing_notes: Optional description of preprocessing steps applied

    Returns:
        Metadata dictionary
    """
    metadata = {
        'dataset_name': dataset_name,
        'download_urls': download_urls,
        'download_timestamp': datetime.now().isoformat(),
        'statistics': {
            'num_samples': num_samples,
            'num_features': num_features,
            'target_stats': target_stats,
        },
    }

    if preprocessing_notes:
        metadata['preprocessing_notes'] = preprocessing_notes

    return metadata


def upload_to_huggingface(
    dataset_name: str,
    data_files: dict[str, str],
    metadata: dict[str, Any],
) -> None:
    """Upload dataset files and metadata to HuggingFace Hub.

    Args:
        dataset_name: Name of the dataset (used for subdirectory naming)
        data_files: Dictionary mapping file names to local file paths
        metadata: Metadata dictionary to save
    """
    try:
        api = huggingface_hub.HfApi()
        repo_id = 'ogbench-neurips/ogbench-neurips'

        # Create repository if it doesn't exist
        try:
            huggingface_hub.create_repo(repo_id=repo_id, repo_type='dataset', exist_ok=True)
        except Exception as e:
            print(f'Did not create repository {repo_id}: {e}')

        # Upload files to root of repository with dataset-specific naming
        uploaded_files = []
        for file_name, file_path in data_files.items():
            if os.path.exists(file_path):
                # Rename files to include dataset name prefix for hf_omics compatibility
                hf_file_name = f'{dataset_name}_{file_name}.parquet'
                result = api.upload_file(
                    path_or_fileobj=file_path,
                    path_in_repo=hf_file_name,
                    repo_id=repo_id,
                    repo_type='dataset',
                )
                uploaded_files.append(hf_file_name)
                print(f'Uploaded {hf_file_name}')
            else:
                print(f'Warning: File {file_path} does not exist')

        # Save metadata as JSON
        metadata_file = f'{dataset_name}_metadata.json'
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json') as f:
            json.dump(metadata, f, indent=2)
            f.flush()
            result = api.upload_file(
                path_or_fileobj=f.name,
                path_in_repo=metadata_file,
                repo_id=repo_id,
                repo_type='dataset',
            )
        print(f'Uploaded {metadata_file}')

        # Display the commit hash generated by Hugging Face
        if hasattr(result, 'commit_hash'):
            print(f'📊 Dataset upload completed with commit hash: {result.commit_hash}')
        elif hasattr(result, 'commit') and hasattr(result.commit, 'oid'):
            print(f'📊 Dataset upload completed with commit hash: {result.commit.oid}')
        else:
            # Try to get the latest commit from the repository
            try:
                repo_info = api.repo_info(repo_id=repo_id, repo_type='dataset')
                if hasattr(repo_info, 'sha'):
                    print(f'📊 Dataset upload completed with commit hash: {repo_info.sha}')
                else:
                    print('📊 Dataset upload completed (commit hash not available)')
            except Exception:
                print('📊 Dataset upload completed (commit hash not available)')

        # Summary of uploaded files
        if uploaded_files:
            print(f'📁 Uploaded files: {", ".join(uploaded_files)}')
            print(f'📄 Uploaded metadata: {metadata_file}')
    except (
        huggingface_hub.utils.RepositoryNotFoundError,
        huggingface_hub.utils.HfHubHTTPError,
    ) as e:
        print(f'⚠️  HuggingFace upload failed (authentication required): {e}')
        print(f'Data files saved locally in temp_data/{dataset_name}/')
        print('To upload later, set up authentication with: huggingface-cli login')
    except Exception as e:
        print(f'⚠️  HuggingFace upload failed: {e}')
        print(f'Data files saved locally in temp_data/{dataset_name}/')
