# Dataset loader config
loader:
  _target_: ogbench.data.loaders.OmicsDatasetLoader
  parameters:
    data_type: omics
    data_domain: graph
    data_name: covidaki
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_type}
    adjacency_threshold: 0.95
    node_sample_ratio: 0.169
    method: variance
    imputation_method: mean
    train_val_test_split: [0.7, 0.15, 0.15]

# Dataset parameters
parameters:
  num_features: 1
  num_classes: 2
  num_samples: 1135
  num_nodes: ${calculate_num_nodes:${dataset.parameters.num_samples},${dataset.loader.parameters.train_val_test_split},${dataset.loader.parameters.node_sample_ratio}} # 4698 # TODO: it depends on the node sample ratio!
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/${dataset.loader.parameters.data_name}/data_splits
  data_seed: 0
  split_type: 'fixed'

# Dataloader parameters
dataloader_params:
  batch_size: 1
  num_workers: 0
  pin_memory: False
  persistent_workers: False
